;; -*- mode: eask; lexical-binding: t -*-

(package "compile-plus"
         "0.0.1"
         "Run M-x `compile' based on buffer content")

(website-url "https://github.com/hron/compile-plus.el")
(keywords "convenience" "compile" "test")

(package-file "compile-plus.el")
(files "compile-plus-helpers.el"
       "compile-plus-python-ts.el"
       "compile-plus-rust-ts.el")

(depends-on "emacs" "29.1")
